# -*- coding: utf-8 -*-
"""2303a52073_aiml-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ih578TdFkPjK1mWavqLyJs9OutAHEYQ3

Lab Exercise - Python Libraries and Packages[CO1] Part 1 – Implement Basic Data Structures using Numpy, Pandas

Lists
Arrays
Identify their type using type()
Perform mathematical operations on these datasets created - multiplication, division, poweroff
Combine text with Numpy fuction to generate a textual output - ”Addition of Two: array1 +array 2
Implement np.sin(), log(), log2(), np.exp())
"""

#1,2,3
import numpy as np
lst1=[21,31.76]
array1 = np.array(lst1)
array1
type(lst1)
type(array1)

list2=[3,2,1]
array2=np.array(list2)
print(array2)

#4
# Ensure arrays have compatible shapes for element-wise operations
array1 = np.array([21, 31.76, 42])  # Add an element to match array2's length
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)

#5
#addition in floating
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")
#addition
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)

#6
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

"""Part 2 – Visualization of Data using matplotlib, pyplots Packages[CO2]

Generate a Data set for Health Care using the following: people = [’kiran’, arun’, ’vijay’, ’varun’] age =[25, 30, 35, 40, 45] height =[145, 151, 165, 173] weight=[45, 55, 65, 75]
Using the generated dataset given above. Generate the following graphs and justify the relationships among the vectors.
Scatter Plot
Bar Chart
Histogram
Provide Graph Title, labels for X, Y axis with proper justification and explanation of the graph.
"""

people = ['ahana','ayaan','amogh','trikshi']
age =[25, 30, 35, 40, 45]
height =[145, 151, 165, 173]
weight=[45, 55, 65, 75]
#2,3
import matplotlib.pyplot as plt
plt.scatter(weight, height)
plt.title("Relationship between Weight and Height of Patients")
plt.ylabel("Height in Meters")
plt.xlabel("Weight of Patients in Kgs")
plt.show()

#bar chart
plt.figure(figsize=(12,4))
plt.title("People's weight in kgs",fontsize=16,
          fontstyle='italic')

# Main plot function 'bar'
plt.bar(x=people,height=weight, width=0.6,
        color='orange',edgecolor='k',alpha=0.6)

plt.xlabel("People",fontsize=15)
plt.xticks(fontsize=14,rotation=30)
plt.yticks(fontsize=14)
plt.ylabel("Weight (in kgs)",fontsize=15)
plt.show()

#histogram
import numpy as np
import matplotlib.pyplot as plt # Import the matplotlib.pyplot module
weight =[45,55,65,75]

plt.figure(figsize=(7,5))

# Main plot function 'hist'
plt.hist(weight,color='red',edgecolor='k', alpha=0.75,bins=5)

plt.title("Histogram of patient weight",fontsize=18)
plt.xlabel("Weight in kgs",fontsize=15)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()

"""Part 3 – Access Data from Various Data Sources using builtin Function of Numpy, Pandas[CO3]

Generate your own dataset using MS Excel and Notepad to prepare the dataset. Save it in Google Drive and access it in Google Colab.
Upload the text file using tab seperated value(.tsv) and access the data from the file.
Upload the text file using comma seperated value(.csv) and access the data from file.
Access the excel file using .xlsx
Access the text from the URL
"""

import numpy as np
import pandas as pd

# Try reading the file with a different encoding
d1 = pd.read_table("/content/name.aiml.txt", encoding='latin-1')  # Or try 'utf-16' or other encodings if this doesn't work

print(d1)
data2 = pd.read_excel("/content/Book1.xlsx")
print(data2)
data3 = pd.read_csv("/content/HistoricalPrices.csv")
print(data3)